<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="MediatR"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Mentoory.Identity.Domain\Mentoory.Identity.Domain.csproj"/>
        <ProjectReference Include="..\Mentoory.Shared.Application\Mentoory.Shared.Application.csproj"/>
    </ItemGroup>
</Project>
