<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="MediatR"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Mentoory.Access.Contracts\Mentoory.Access.Contracts.csproj"/>
        <ProjectReference Include="..\Mentoory.Access.Domain\Mentoory.Access.Domain.csproj"/>
        <ProjectReference Include="..\Mentoory.Notification.Contracts\Mentoory.Notification.Contracts.csproj"/>
        <ProjectReference Include="..\Mentoory.Shared.Application\Mentoory.Shared.Application.csproj"/>
    </ItemGroup>
</Project>
