<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="MediatR"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Mentoory.Access.Domain\Mentoory.Access.Domain.csproj"/>
        <ProjectReference Include="..\Mentoory.Shared.Application\Mentoory.Shared.Application.csproj"/>
        <ProjectReference Include="..\Mentoory.Tenant.Domain\Mentoory.Tenant.Domain.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="Mentoory.Access.Tests"/>
    </ItemGroup>
</Project>
