<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="MediatR"/>
        <PackageReference Include="Microsoft.Extensions.Options"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Mentoory.Access.Contracts\Mentoory.Access.Contracts.csproj"/>
        <ProjectReference Include="..\Mentoory.Tenant.Contracts\Mentoory.Tenant.Contracts.csproj"/>
        <ProjectReference Include="..\Mentoory.Notification.Domain\Mentoory.Notification.Domain.csproj"/>
        <ProjectReference Include="..\Mentoory.Shared.Application\Mentoory.Shared.Application.csproj"/>
    </ItemGroup>
</Project>
