<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <InternalsVisibleTo Include="Mentoory.Knowledge.Tests"/>
        <InternalsVisibleTo Include="Mentoory.Knowledge.Application"/>
        <InternalsVisibleTo Include="Mentoory.Knowledge.Infrastructure"/>
        <InternalsVisibleTo Include="Mentoory.Tests.Integration"/>
    </ItemGroup>
    <ItemGroup>
        <PackageReference Include="MediatR.Contracts"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Mentoory.Shared.Domain\Mentoory.Shared.Domain.csproj"/>
    </ItemGroup>
</Project>
