<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer"/>
        <PackageReference Include="MediatR"/>
        <PackageReference Include="RazorLight"/>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Templates\*.cshtml"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Mentoory.Tenant.Domain\Mentoory.Tenant.Domain.csproj"/>
        <ProjectReference Include="..\Mentoory.Shared.Infrastructure\Mentoory.Shared.Infrastructure.csproj"/>
    </ItemGroup>
</Project>
