<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="coverlet.collector"/>
        <PackageReference Include="FluentAssertions"/>
        <PackageReference Include="Microsoft.NET.Test.Sdk"/>
        <PackageReference Include="Moq"/>
        <PackageReference Include="xunit"/>
        <PackageReference Include="xunit.runner.visualstudio"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\Mentoory.Notification.Domain\Mentoory.Notification.Domain.csproj"/>
        <ProjectReference Include="..\..\Mentoory.Notification.Application\Mentoory.Notification.Application.csproj"/>
    </ItemGroup>
</Project>
