<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="FluentValidation"/>
        <PackageReference Include="MediatR"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Mentoory.Tenant.Domain\Mentoory.Tenant.Domain.csproj"/>
        <ProjectReference Include="..\Mentoory.Shared.Application\Mentoory.Shared.Application.csproj"/>
        <ProjectReference Include="..\Mentoory.Access.Application\Mentoory.Access.Application.csproj"/>
        <ProjectReference Include="..\Mentoory.Knowledge.Domain\Mentoory.Knowledge.Domain.csproj"/>
    </ItemGroup>
</Project>
