<Project Sdk="Microsoft.NET.Sdk">
    <ItemGroup>
        <PackageReference Include="Aspire.Microsoft.EntityFrameworkCore.SqlServer"/>
        <PackageReference Include="MailKit"/>
        <PackageReference Include="MediatR"/>
        <PackageReference Include="RazorLight"/>
        <PackageReference Include="UAParser"/>
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\Mentoory.Notification.Application\Mentoory.Notification.Application.csproj"/>
        <ProjectReference Include="..\Mentoory.Notification.Domain\Mentoory.Notification.Domain.csproj"/>
        <ProjectReference Include="..\Mentoory.Shared.Infrastructure\Mentoory.Shared.Infrastructure.csproj"/>
    </ItemGroup>
    <ItemGroup>
        <EmbeddedResource Include="Templates\*.cshtml"/>
    </ItemGroup>
</Project>
